[package]
edition = "2021"
name = "yfb_derive"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
darling = "0.20"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
Inflector = { version = "0.11", default-features = false }
